name: Bloqbit Test Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.7.0'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run tests
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          TEST_GUILDED_TOKEN: ${{ secrets.TEST_GUILDED_TOKEN }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          TEST_LOG_WH: ${{ secrets.TEST_LOG_WH }}
        run: npm run test

      - name: Clean up build artifacts
        run: npm run clean